# Generated by Django 4.0.2 on 2022-03-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zaiko_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=12, max_length=8),
            preserve_default=False,
        ),
    ]
