# Generated by Django 4.0.2 on 2022-05-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zaiko_App', '0002_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
