# Generated by Django 4.0.2 on 2022-06-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zaiko_App', '0005_alter_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=4)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('profit', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
